// AUTOGENERATED FILE DO NOT EDIT
namespace ValueFactoryVRCRouterCommon {
  public static class Build {
    #if DEBUG
      public static string build_version = "DEBUG";
      public static string build_date = "DEBUG";
    #else
      public static string build_version = "1.0.3";
      public static string build_date = "2024-04-12 17:14:42";
    #endif
  }
}
